<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXIGxxGb\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXIGxxGb/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXIGxxGb.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXIGxxGb\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXIGxxGb\App_KernelProdContainer([
    'container.build_hash' => 'XIGxxGb',
    'container.build_id' => '4fb5f431',
    'container.build_time' => 1655109717,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXIGxxGb');
