<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMmHLT6Q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMmHLT6Q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMmHLT6Q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMmHLT6Q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMmHLT6Q\App_KernelDevDebugContainer([
    'container.build_hash' => 'MmHLT6Q',
    'container.build_id' => '39206de2',
    'container.build_time' => 1655367981,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMmHLT6Q');
