<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGjqY73j\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGjqY73j/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGjqY73j.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGjqY73j\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGjqY73j\App_KernelDevDebugContainer([
    'container.build_hash' => 'GjqY73j',
    'container.build_id' => '6f21cc2b',
    'container.build_time' => 1655478749,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGjqY73j');
