<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD872DxQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD872DxQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD872DxQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD872DxQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD872DxQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'D872DxQ',
    'container.build_id' => 'ab67cbae',
    'container.build_time' => 1663629635,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD872DxQ');
